server.port : 8084
camel:
  sourceLocation : file:src/main/resources/source
  destinationLocation1: file:src/main/resources/Destination
#  destinationLocation2: file:src/main/resources/Destination
#  destinationLocation3: file:src/main/resources/Destination
  component:
    kafka:
      brokers: localhost:9092

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: College_Admin
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.requestConsumer.serdes.CollegeAdmissionSerializer
    consumer:
      group-id: admission-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.requestConsumer.serdes.CollegeAdmissionDeserializer

